-- liquibase formatted sql
-- changeset zbiir:4

CREATE TABLE ORDERS (
    ID BIGINT NOT  NULL AUTO_INCREMENT,
    ID_CUSTOMER BIGINT NOT NULL ,
    PRICE float(6,2),
    START_DATE date,
    PLANED_FINISH_DATE date,
    IS_READY BOOLEAN,
    IS_PAID BOOLEAN,
    PRIMARY KEY (ID),

    FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMERS(ID)
)


-- changeset zbiir:5
CREATE TABLE UNIT_ORDER (
    ID BIGINT NOT  NULL AUTO_INCREMENT,
    ID_ORDER BIGINT,
    SERVED_UNIT BIGINT,
    TAG_LABEL varchar(10),
    COMMENT varchar(100),
    UNIT_PRICE float(6,2),
    FINISH_DATE date,


    PRIMARY KEY (ID),
    FOREIGN KEY (ID_ORDER) REFERENCES ORDERS(ID),
    FOREIGN KEY (SERVED_UNIT) REFERENCES SERVED_UNIT(ID)

)
