-- liquibase formatted sql
-- changeset zbiir:6
CREATE TABLE ORDER_ARCHIVE (
    ID BIGINT NOT  NULL,
    ID_CUSTOMER BIGINT NOT NULL ,
    PRICE float(6,2),
    START_DATE date,
    PLANED_FINISH_DATE date,
    PICKUP_DATE date,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMERS(ID)
)
-- changeset zbiir:7
CREATE TABLE UNIT_ORDER_ARCHIVE (
    ID BIGINT NOT NULL,
    ID_ORDER BIGINT,
    SERVED_UNIT BIGINT,
    TAG_LABEL varchar(10),
    COMMENT varchar(100),
    UNIT_PRICE float(6,2),
    FINISH_DATE date,

    PRIMARY KEY (ID),
    FOREIGN KEY (ID_ORDER) REFERENCES ORDER_ARCHIVE(ID),
    FOREIGN KEY (SERVED_UNIT) REFERENCES SERVED_UNIT(ID)
)